### ISSUE TITLE
Issue while trying to create an application resource

### ISSUE THREAD

**Issue by juliopovedacs** [OpenMTC/OpenMTC#44]
Hello. 

I am following the **Quick Start** tutorial: https://www.openmtc.org/doc.html

After cloning the repository, building the gateway image, and running it, I am facing issues. When I try to create an **application resource** (by running the corresponding command that appears in the **Quick Start** tutorial), the following message appears on my terminal window: 

`"Failed to connect to localhost port 8000: Connection refused".`

I opened **Docker Desktop**'s dashboard to check the gateway container log, and I found the following:

<img width="1108" alt="ERROR" src="https://user-images.githubusercontent.com/14988536/75599470-23685380-5a73-11ea-9452-c54fbd759113.png">

Can someone help me please?

Thank you.

**Comment by mKay00** [comment]
I have a related issue. I am trying to run the minimal application from https://fiware-openmtc.readthedocs.io/en/latest/sdk-framework/index.html and when I run it, I get the same ImportError of 'Accept' as you in the same file.

```
Traceback (most recent call last):
  File "client.py", line 1, in <module>
    from openmtc_app.onem2m import XAE
  File "/usr/local/lib/python3.5/dist-packages/openmtc_app/onem2m.py", line 28, in <module>
    from openmtc_app.notification import NotificationManager
  File "/usr/local/lib/python3.5/dist-packages/openmtc_app/notification/__init__.py", line 11, in <module>
    from openmtc_onem2m.serializer import get_onem2m_decoder
  File "/usr/local/lib/python3.5/dist-packages/openmtc_onem2m/serializer/__init__.py", line 3, in <module>
    from werkzeug import Accept, parse_accept_header
ImportError: cannot import name 'Accept'
```

My guess is that there is a version incompatibility, but I am not sure. I am going to try different versions tomorrow, maybe I find a working one. 
Currently, I am using:
- Python 3.5.3
- werkzeug 1.0.0
- openMTC latest master

**Comment by CodeOne91** [comment]
I solved the same problem using werkzeug 0.16. 
Worked for me.

**Comment by juliopovedacs** [comment]
Hello.

Thanks @mKay00 and @CodeOne91 for your comments.

@CodeOne91 how can I downgrade `werkzeug` please? I execute `pip3 freeze` in my terminal window and `werkzeug` does not even appear.

Thank you for your help.

**Comment by juliopovedacs** [comment]
I found there is a **dependencies.txt** file inside **openmtc-gevent**, and it has the following line: `werkzeug>=0.9`. 

So, I changed it to `werkzeug==0.16`, saved the file, deleted the previous **gateway image** I had built  and created a new **gateway image** (with the `./create-binary-docker gateway` command). 

However, I still get the `"Failed to connect to localhost port 8000: Connection refused"` when I try to create an **application resource**.

I checked my terminal window and my change to the `werkzeug` version was ignored.

Can someone help me please?


Thank you.

**Comment by juliopovedacs** [comment]
Hello.


I was able to downgrade werkzeug to version 0.16 as @CodeOne91 said by editing the following files:

1. **openmtc-gevent/dependencies.txt**
   Changed line 9: `werkzeug==0.16`
2. **setup-sdk.py**
    Changed line 21: `"urllib3", "gevent (>=1.0)", "iso8601 (>=0.1.5)", "werkzeug (==0.16)",`
    Changed line 26: `"urllib3", "gevent >= 1.0", "iso8601 >= 0.1.5", "werkzeug == 0.16",`
3. **setup-gevent-all.py**
    Changed line 27: `"urllib3", "gevent (>=1.0)", "iso8601 (>=0.1.5)", "werkzeug (==0.16)",`
    Changed line 35: `"urllib3", "gevent >= 1.0", "iso8601 >= 0.1.5", "werkzeug == 0.16",`

With these changes, deleting previous built gateway image and building a new gateway image, OpenMTC works again.

**Comment by CodeOne91** [comment]
@japoveda10 sorry for being late. You can try this command in future:
`sudo -H pip3 install Werkzeug==0.16.0`
python version 3.5

**Comment by juliopovedacs** [comment]
No worries. Thank you @CodeOne91!
