### ISSUE TITLE
why MQTTS is not working 

### ISSUE THREAD

**Issue by janaka1984** [OpenMTC/OpenMTC#9]
Hi @rst-fokus ,

I need to use secure MQTT connection with openmtc. i have used an own mqtt broker (EMQ) which enable SSL and use  key and certs file itself. Afterthat i changed openmtc-backend.json as follow (1). when i run  ./run-backend, it returned error (2)

(1)
```
{
                "name": "MQTTTransportPlugin",
                "package": "openmtc_cse.plugins.transport_gevent_mqtt",
                "disabled": false,
                "config": {
                    "interface": "x.x.x.x",
                    "port": 8883
                }
            }
```

(2)

> ERROR:MQTTTransportPlugin:Failed to start plugin
> Traceback (most recent call last):
>   File "/home/privacy/src/OpenMTC/server/openmtc-server/src/openmtc_server/Plugin.py", line 37, in start
>     self._start()
>   File "/home/privacy/src/OpenMTC/server/openmtc-cse/src/openmtc_cse/plugins/transport_gevent_mqtt/__init__.py", line 45, in _start
>     client_id=self.config['onem2m'].get('cse_id'),
>   File "/home/privacy/src/OpenMTC/common/openmtc-onem2m/src/openmtc_onem2m/client/mqtt.py", line 74, in get_client
>     cert_file=cert_file, key_file=key_file, insecure=insecure
>   File "/home/privacy/src/OpenMTC/common/openmtc-onem2m/src/openmtc_onem2m/client/mqtt.py", line 288, in __init__
>     raise ConnectionFailed(e.message)
> ConnectionFailed
> ERROR:openmtc_gevent.main:Error during startup
> Traceback (most recent call last):
>   File "/home/privacy/src/OpenMTC/openmtc-gevent/src/openmtc_gevent/main.py", line 389, in main
>     start_plugins()
>   File "/home/privacy/src/OpenMTC/openmtc-gevent/src/openmtc_gevent/main.py", line 141, in start_plugins
>     async_all([plugin.start() for plugin in _plugins]).get()
>   File "/home/privacy/src/OpenMTC/common/openmtc/lib/aplus/__init__.py", line 128, in get
>     raise self.reason
> ConnectionFailed

When i did same thing for https, i could see and enable following on config-backend.json
```
 "enable_https": true,
  "require_cert": true
```
But MQTTTransportPlugin does not give like that configuration

can you explain what's wrong with this mqtts?

**Comment by rst-fokus** [comment]
Hello @janaka1984 ,

We are currently working on improving/fixing MQTTS. I will give you an update beginning of next week.

Best,
Ronald

**Comment by janaka1984** [comment]
thanks Ronald

**Comment by janaka1984** [comment]
Hi @ckl-fokus  @rst-fokus 

can i know whether MQTTS issue is solved in latest OpenMTC
